services:
  redis:
    image: redis:alpine

  mongodb:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017" # Exponemos el puerto para conectarnos desde tu máquina local
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  # celery-worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     - PIP_DEFAULT_TIMEOUT=100
  #     - DATABASE=postgres
  #   env_file:
  #     - ./.envrc
  #   volumes:
  #     - ./src:/project_django/src
  #     - ./config:/project_django/config
  #     - ./tests:/tests
  #     - ${HOME}/.aws:/home/user/.aws:ro
  #     - ${HOME}/.gitconfig:/home/user/.gitconfig:ro
  #     - ${HOME}/.ssh:/home/user/.ssh:ro
  #   depends_on:
  #     - postgres
  #   command: celery -A src.messaging.app worker -l info

  # celery_beat:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     - PIP_DEFAULT_TIMEOUT=100
  #     - DATABASE=postgres
  #   env_file:
  #     - ./.envrc
  #   volumes:
  #     - ./src:/project_django/src
  #     - ./config:/project_django/config
  #     - ${HOME}/.aws:/home/user/.aws:ro
  #     - ${HOME}/.gitconfig:/home/user/.gitconfig:ro
  #     - ${HOME}/.ssh:/home/user/.ssh:ro
  #   depends_on:
  #     - postgres
  #   command: celery -A src.messaging.app beat -l info

  worker:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PIP_DEFAULT_TIMEOUT=100
      - DATABASE=postgres
    env_file:
      - ./.envrc
    ports:
      - '8000:8000'
    volumes:
      - ./src:/project_django/src
      - ./communication:/project_django/communication
      - ./django_apps:/project_django/django_apps
      - ./django_project:/project_django/django_project
      - ./shared:/project_django/shared
      - ${HOME}/.aws:/home/user/.aws:ro
      - ${HOME}/.gitconfig:/home/user/.gitconfig:ro
      - ${HOME}/.ssh:/home/user/.ssh:ro
    depends_on:
      - mongodb

volumes:
  mongo_data:
    driver: local