# Generated by Django 4.1.13 on 2025-01-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("document", models.CharField(blank=True, max_length=50)),
                ("code_phone", models.CharField(blank=True, max_length=10)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("profile_image", models.CharField(blank=True, max_length=250)),
                ("is_anonymous", models.BooleanField(default=True)),
                ("password", models.CharField(max_length=128)),
                ("is_authenticated", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
